### ISSUE TITLE
Errors while trying to run the app

### ISSUE THREAD

**Issue by mlubbad-2p** [WeferralHq/weferral#27]
After running this command below:
`npm start`

I got these issues
`ERROR in ./app/styles/plugins/plugins.scss
Module build failed (from ./node_modules/extract-css-chunks-webpack-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):

$half-drag-handle-height: math.div($drag-handle-height, 2);
                             ^
      Invalid CSS after "...le-height: math": expected expression (e.g. 1px, bold), was ".div($drag-handle-h"
      in /home/ubuntu/weferral/node_modules/react-image-crop/lib/ReactCrop.scss (line 21, column 31)
    at /home/ubuntu/weferral/node_modules/webpack/lib/NormalModule.js:316:20
    at /home/ubuntu/weferral/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /home/ubuntu/weferral/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/home/ubuntu/weferral/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.callback (/home/ubuntu/weferral/node_modules/sass-loader/dist/index.js:89:7)
    at Object.done [as callback] (/home/ubuntu/weferral/node_modules/neo-async/async.js:8069:18)
    at options.error (/home/ubuntu/weferral/node_modules/node-sass/lib/index.js:294:32)
 @ ./app/layout/default.js 39:0-42
 @ ./app/components/App/AppClient.js
 @ ./app/components/App/index.js
 @ ./app/index.js
 @ multi ./app/index.js

ERROR in ./app/routes/index.js
Module not found: Error: Can't resolve './Pages/Email' in '/home/ubuntu/weferral/app/routes'
 @ ./app/routes/index.js 28:0-34 173:15-20
 @ ./app/components/App/AppClient.js
 @ ./app/components/App/index.js
 @ ./app/index.js
 @ multi ./app/index.js
`
Could you advice?

**Comment by rinshadka** [comment]
@mlubbad-2p , Did you get a solution for this error?
Thanks
